### ISSUE TITLE
OpenCAP alias support

### ISSUE THREAD

**Issue by lane-c-wagner** [blocktrail/blocktrail-wallet#108]
Blocktrail could easily add "Send to alias" feature using the OpenCAP alias protocol. I can help with this, I'll submit a PR soon.

protocol: https://github.com/opencap/protocol

reference server: https://ogdolo.com

*Edit: There are some issues with installation that aren't addresses in the docs. I don't think the installation should be causing changes to the committed files. I still think it would be awesome if you guys added this feature but I won't be able to contribute personally until the installation process is a bit more streamlined.

**Comment by lacksfish** [comment]
Alias registration is always subject to some degree of name-squatting (even on top of DNS) and similar looking handles cause additional confusion.

Primarily, concerns arise on the storage of address-alias relations. As you yourself state in the protocol readme:

> The most obvious way for a malicious party to use the alias system to steal funds would be to hack a OpenCAP server and secretly change out addresses so that their address is associated with someone else's alias.

It looks to be an intriguing project, thank you for sharing. Have you had a chance to look at the "Send to Contacts" feature that the BTC.com Blocktrail wallet provides? You can send to your phone contacts by name, once both parties verify their phone number in the wallet app.

**Comment by lane-c-wagner** [comment]
Yeah, I was just hoping that you guys would be interested in a more global
and less centralized solution. The great thing about OpenCAP is the
paranoid users can run their own servers (or not use it) and the more
trusting users can use a third party service.
