### ISSUE TITLE
Cannot send email

### ISSUE THREAD

**Issue by fortran77** [blocktrail/blocktrail-wallet#11]
Android 6.01, on a Nexus 9, with a freshly-installed Blocktrail app.

Created new account with username and password. Following the prompts, I try to make a backup and it says:

```
Sorry

You don't have a default mail account configured on this
phone.

Please configure your mail app, or you can skip this step and
save your backup later when we support alternative apps.
```

Android 6 by default includes no "mail app" other than the standard Gmail app.

This Nexus 9 does have a Google login (for use by the Google Play Store), and it also has the Gmail app logged into a gmail account.

**Comment by lacksfish** [comment]
Saving your backup PDF supports many options for a long time now, not only email. Closing therefore.

Searching for the backup PDF? Try this link:
https://help.btc.com/hc/en-us/articles/360002937174-I-have-lost-my-backup-PDF-where-could-it-be-
