### ISSUE TITLE
Will version 4.4.7 of the app be open sourced?

### ISSUE THREAD

**Issue by lacksfish** [blocktrail/blocktrail-wallet#122]
I see the Google Play store release of the BTC.com wallet is version 4.4.7 since 3rd of April 2019.

Will this version be open sourced on this projects master branch? The last release on master is version 4.4.4.

As some webpages with Bitcoin/Bitcoin Cash wallet comparisons do list this wallet as being open source, it would be beneficial to make the latest version available on GitHub?

**Comment by lsgrep** [comment]
Hi @lacksfish, the mobile version was released in order to fix ReCaptcha related issues, will be open sourced soon.

**Comment by lacksfish** [comment]
Looking forward, maybe more developers can contribute then :)

**Comment by lacksfish** [comment]
@lsgrep Please open source the latest version of the BTC.com wallet :pray:

**Comment by RLlane9** [comment]
Git

**Comment by lsgrep** [comment]
Hi, the master branch has been updated. Latest updates are recaptcha related, which was long overdued. apologies. If you have any further issues, please reopen the issue.
